package com.interview.datacollect.mapper;

import com.interview.datacollect.pojo.Cpu;
import com.interview.datacollect.pojo.CpuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    long countByExample(CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int deleteByExample(CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int insert(Cpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int insertSelective(Cpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    List<Cpu> selectByExample(CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    Cpu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Cpu record, @Param("example") CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int updateByExample(@Param("record") Cpu record, @Param("example") CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int updateByPrimaryKeySelective(Cpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpu
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    int updateByPrimaryKey(Cpu record);
}