package com.interview.datacollect.mapper;

import com.interview.datacollect.pojo.Disk;
import com.interview.datacollect.pojo.DiskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    long countByExample(DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int deleteByExample(DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int insert(Disk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int insertSelective(Disk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    List<Disk> selectByExample(DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    Disk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Disk record, @Param("example") DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByExample(@Param("record") Disk record, @Param("example") DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByPrimaryKeySelective(Disk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disk
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByPrimaryKey(Disk record);
}