package com.interview.datacollect.mapper;

import com.interview.datacollect.pojo.Net;
import com.interview.datacollect.pojo.NetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    long countByExample(NetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int deleteByExample(NetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int insert(Net record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int insertSelective(Net record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    List<Net> selectByExample(NetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    Net selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Net record, @Param("example") NetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByExample(@Param("record") Net record, @Param("example") NetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByPrimaryKeySelective(Net record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    int updateByPrimaryKey(Net record);
}