package com.interview.datacollect.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Cpu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpu.id
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpu.cpu_usage
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    private BigDecimal cpuUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpu.collect_time
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpu.id
     *
     * @return the value of t_cpu.id
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpu.id
     *
     * @param id the value for t_cpu.id
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpu.cpu_usage
     *
     * @return the value of t_cpu.cpu_usage
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    public BigDecimal getCpuUsage() {
        return cpuUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpu.cpu_usage
     *
     * @param cpuUsage the value for t_cpu.cpu_usage
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    public void setCpuUsage(BigDecimal cpuUsage) {
        this.cpuUsage = cpuUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpu.collect_time
     *
     * @return the value of t_cpu.collect_time
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpu.collect_time
     *
     * @param collectTime the value for t_cpu.collect_time
     *
     * @mbg.generated Wed Apr 29 20:32:38 CST 2020
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}