package com.interview.datacollect.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Disk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disk.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disk.disk_usage
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private BigDecimal diskUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disk.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disk.id
     *
     * @return the value of t_disk.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disk.id
     *
     * @param id the value for t_disk.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disk.disk_usage
     *
     * @return the value of t_disk.disk_usage
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public BigDecimal getDiskUsage() {
        return diskUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disk.disk_usage
     *
     * @param diskUsage the value for t_disk.disk_usage
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setDiskUsage(BigDecimal diskUsage) {
        this.diskUsage = diskUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disk.collect_time
     *
     * @return the value of t_disk.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disk.collect_time
     *
     * @param collectTime the value for t_disk.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}