package com.interview.datacollect.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Memory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_memory.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_memory.mem_usage
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private BigDecimal memUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_memory.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_memory.id
     *
     * @return the value of t_memory.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_memory.id
     *
     * @param id the value for t_memory.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_memory.mem_usage
     *
     * @return the value of t_memory.mem_usage
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public BigDecimal getMemUsage() {
        return memUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_memory.mem_usage
     *
     * @param memUsage the value for t_memory.mem_usage
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setMemUsage(BigDecimal memUsage) {
        this.memUsage = memUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_memory.collect_time
     *
     * @return the value of t_memory.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_memory.collect_time
     *
     * @param collectTime the value for t_memory.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}