package com.interview.datacollect.pojo;

import java.util.Date;

public class Net {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_net.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_net.tx
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Integer tx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_net.rx
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Integer rx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_net.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_net.id
     *
     * @return the value of t_net.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_net.id
     *
     * @param id the value for t_net.id
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_net.tx
     *
     * @return the value of t_net.tx
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Integer getTx() {
        return tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_net.tx
     *
     * @param tx the value for t_net.tx
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setTx(Integer tx) {
        this.tx = tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_net.rx
     *
     * @return the value of t_net.rx
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Integer getRx() {
        return rx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_net.rx
     *
     * @param rx the value for t_net.rx
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setRx(Integer rx) {
        this.rx = rx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_net.collect_time
     *
     * @return the value of t_net.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_net.collect_time
     *
     * @param collectTime the value for t_net.collect_time
     *
     * @mbg.generated Wed Apr 29 22:34:42 CST 2020
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}